In [ ]:
# import libraries

import pandas as pd
import numpy as np
import sklearn as sk

# load data

salary_data = pd.read_csv("/workspaces/week_6/2025_salaries.csv", header=1, encoding="latin-1")
stats = pd.read_csv("/workspaces/week_6/nba_2025.txt", sep=",", encoding="latin-1")

In [ ]:
# merge the dataframes based on Player

merged_data = pd.merge(salary_data, stats, on="Player")

# check for duplicate Player rows

duplicates = merged_data[merged_data.duplicated(subset="Player", keep=False)]
duplicates.head()

,Player,Tm,2025-26,Rk,Age,Team,Pos,G,GS,MP,...,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards,Player-additional
0,Garrison Mathews,IND,"$131,970",398.0,29.0,IND,SG,15.0,1.0,196.0,...,17.0,10.0,6.0,3.0,3.0,19.0,78.0,0.0,NaN,mathega01
1,Garrison Mathews,IND,"$131,970",398.0,29.0,IND,SG,15.0,1.0,196.0,...,17.0,10.0,6.0,3.0,3.0,19.0,78.0,0.0,NaN,mathega01
2,Mac McClung,IND,"$164,060",459.0,27.0,2TM,SG,4.0,0.0,47.0,...,5.0,2.0,5.0,2.0,3.0,8.0,23.0,0.0,NaN,mccluma01
3,Mac McClung,IND,"$164,060",459.0,27.0,IND,SG,3.0,0.0,34.0,...,4.0,1.0,5.0,1.0,2.0,6.0,19.0,0.0,NaN,mccluma01
4,Mac McClung,IND,"$164,060",459.0,27.0,CHI,SG,1.0,0.0,13.0,...,1.0,1.0,0.0,1.0,1.0,2.0,4.0,0.0,NaN,mccluma01

In [ ]:
# sort so that rows with highest G come first

merged_data = merged_data.sort_values(by='G', ascending=False)

# drop duplicate player rows that are not the highest G

merged_cleaned = merged_data.drop_duplicates(subset='Player', keep='first').reset_index(drop=True)
merged_cleaned.head()

,Player,Tm,2025-26,Rk,Age,Team,Pos,G,GS,MP,...,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards,Player-additional
0,Julius Randle,MIN,"$30,864,198",10.0,31.0,MIN,PF,56.0,56.0,1882.0,...,391.0,302.0,62.0,14.0,144.0,159.0,1251.0,3.0,NaN,randlju01
1,Toumani Camara,POR,"$2,221,677",78.0,25.0,POR,PF,56.0,56.0,1873.0,...,300.0,144.0,56.0,25.0,111.0,178.0,734.0,0.0,NaN,camarto01
2,Donte DiVincenzo,MIN,"$11,990,000",84.0,29.0,MIN,SG,56.0,56.0,1745.0,...,251.0,234.0,79.0,25.0,84.0,144.0,716.0,0.0,NaN,divindo01
3,DeMar DeRozan,SAC,"$24,570,000",25.0,36.0,SAC,PF,56.0,56.0,1813.0,...,177.0,211.0,65.0,14.0,63.0,114.0,1047.0,0.0,NaN,derozde01
4,Naz Reid,MIN,"$21,551,724",63.0,26.0,MIN,C,56.0,2.0,1468.0,...,359.0,139.0,57.0,52.0,90.0,141.0,793.0,0.0,NaN,reidna01

In [ ]:
# check for variables with null values
# merged_cleaned.isnull().sum()

In [ ]:
# keep columns that are likely the most related to salary

columns_to_keep = ['Player', '2025-26', 'Rk', 'Age', 'G', '3P%', '2P%', 'eFG%', 'FT%', 'TRB', 
                   'PTS', 'Trp-Dbl']
X = merged_cleaned[columns_to_keep]

# drop null values

X = X.dropna()
X.head()

,Player,2025-26,Rk,Age,G,3P%,2P%,eFG%,FT%,TRB,PTS,Trp-Dbl
0,Julius Randle,"$30,864,198",10.0,31.0,56.0,0.325,0.563,0.540,0.823,391.0,1251.0,3.0
1,Toumani Camara,"$2,221,677",78.0,25.0,56.0,0.370,0.584,0.564,0.702,300.0,734.0,0.0
2,Donte DiVincenzo,"$11,990,000",84.0,29.0,56.0,0.383,0.504,0.557,0.753,251.0,716.0,0.0
3,DeMar DeRozan,"$24,570,000",25.0,36.0,56.0,0.336,0.525,0.521,0.864,177.0,1047.0,0.0
4,Naz Reid,"$21,551,724",63.0,26.0,56.0,0.385,0.574,0.576,0.738,359.0,793.0,0.0

In [ ]:
# remove $ and , in 2025-26 and convert into float

X["2025-26"] = X["2025-26"].str.replace("[$,]", "", regex=True).astype(float)
X.head()

,Player,2025-26,Rk,Age,G,3P%,2P%,eFG%,FT%,TRB,PTS,Trp-Dbl
0,Julius Randle,30864198.0,10.0,31.0,56.0,0.325,0.563,0.540,0.823,391.0,1251.0,3.0
1,Toumani Camara,2221677.0,78.0,25.0,56.0,0.370,0.584,0.564,0.702,300.0,734.0,0.0
2,Donte DiVincenzo,11990000.0,84.0,29.0,56.0,0.383,0.504,0.557,0.753,251.0,716.0,0.0
3,DeMar DeRozan,24570000.0,25.0,36.0,56.0,0.336,0.525,0.521,0.864,177.0,1047.0,0.0
4,Naz Reid,21551724.0,63.0,26.0,56.0,0.385,0.574,0.576,0.738,359.0,793.0,0.0

In [ ]:
# scale only numeric columns

from sklearn.preprocessing import StandardScaler

X_scaled = X.copy()
scaler = StandardScaler()
X_scaled.iloc[:, 1:] = scaler.fit_transform(X.iloc[:, 1:])
X_scaled.head()

,Player,2025-26,Rk,Age,G,3P%,2P%,eFG%,FT%,TRB,PTS,Trp-Dbl
0,Julius Randle,1.339766,-1.555079,1.074376,1.287844,-0.112648,0.294063,0.069293,0.454950,2.077163,2.456437,3.725933
1,Toumani Camara,-0.749496,-1.049289,-0.274679,1.287844,0.280796,0.519848,0.394194,-0.576088,1.266789,0.895665,-0.188314
2,Donte DiVincenzo,-0.036969,-1.004660,0.624691,1.287844,0.394458,-0.340284,0.299431,-0.141518,0.830434,0.841324,-0.188314
3,DeMar DeRozan,0.880650,-1.443507,2.198589,1.287844,-0.016472,-0.114500,-0.187921,0.804310,0.171448,1.840581,-0.188314
4,Naz Reid,0.660489,-1.160860,-0.049836,1.287844,0.411944,0.412332,0.556645,-0.269333,1.792197,1.073780,-0.188314

In [ ]:
# prep data for model by dropping Player and salary

features = X_scaled.drop(columns=["Player", "2025-26"])

In [ ]:
# KMeans clustering with best guess for k

from sklearn.cluster import KMeans
kmeans_obj = KMeans(n_clusters=5, random_state=42).fit(features)

In [30]:
# examine clustering results

print(f"Cluster centers: {kmeans_obj.cluster_centers_}")
print(f"Cluster labels: {kmeans_obj.labels_}")
print(f"Inertia: {kmeans_obj.inertia_}")

Cluster centers: [[-1.25011708  0.11076557  0.67745535 -0.11077402 -0.00775101 -0.06995067
   0.00881588  1.64653271  1.54990372  4.09871842]
 [ 1.29160298 -0.09480473 -1.24580467 -0.65487164 -1.07856507 -1.37448738
  -0.10814464 -1.04337085 -1.02430663 -0.1883143 ]
 [-1.09514546  0.08218139  0.74730669  0.16769631  0.23073714  0.34240357
   0.25990545  0.95706753  1.14310374 -0.12846343]
 [ 0.9716541   0.25389839 -0.93070955  0.52591277  0.94538762  1.09363431
  -0.18801009 -0.70860525 -0.85847623 -0.1883143 ]
 [ 0.02697319 -0.13035415  0.24904    -0.05008642 -0.09604746 -0.10953103
  -0.07599907 -0.16472344 -0.24260417 -0.14423494]]
Cluster labels: [0 2 2 2 2 2 4 2 4 2 4 2 4 4 4 2 2 4 2 0 2 2 0 2 2 4 2 4 2 2 2 2 2 2 2 4 2
 2 2 4 2 2 4 2 4 2 4 2 2 4 4 2 2 4 2 2 4 2 0 2 2 4 4 4 2 2 2 2 2 2 2 4 2 4
 2 2 4 2 2 4 2 4 2 2 2 4 2 0 2 2 0 2 3 2 2 2 4 2 2 2 4 4 0 2 4 2 4 2 4 4 2
 2 4 4 2 2 2 4 2 2 2 4 2 4 1 2 4 4 4 2 2 2 4 0 4 4 4 4 4 4 4 4 0 4 4 0 4 4
 4 4 2 4 2 2 4 4 4 4 3 4 2 2 4 4 4 3 4 4 4 0 3 4 4 4 4 4 1 2 4 4 4 4 2 3 4
 0 2 0 2 4 1 2 4 2 4 2 3 4 4 2 4 4 2 2 4 4 4 4 2 2 2 2 4 4 3 2 4 4 4 4 3 3
 3 4 4 4 3 2 2 4 4 1 3 1 3 4 2 4 3 2 3 4 3 4 4 4 4 4 4 4 4 3 1 2 4 4 4 4 1
 4 4 4 4 4 1 0 4 1 1 3 3 4 1 4 4 4 3 4 3 4 3 3 4 4 3 4 4 3 4 3 3 2 2 1 4 3
 1 4 3 3 4 4 1 1 3 1 3 4 3 1 4 1 4 4 3 2 4 4 4 1 1 1 4 4 1 1 1 1 1 3 3 1 3
 3 1 1 1 1 1 3 1 1 4 1 1 1 1 1 1 1 4 1 1 3 3 1 3 1 1 3 3 1 1 1 3 3 3 1 3 3
 1 1 1 3 1 1 1 1 3 3 3 1 3 1 3 3 1 3]
Inertia: 2196.962515381002

In [ ]:
# visualize clusters in 3D

import plotly.express as px

fig = px.scatter_3d(
    X_scaled, x="eFG%", y="PTS", z="G", # 3 chosen variables
    color="2025-26", # color indicates salary
    symbol=kmeans_obj.labels_, # shape indicates cluster
    hover_data=["Player"]) # check which point is which Player
fig.show(renderer="browser")

In [ ]:
# calculate variance explained

# first calculate total sum of squares (TSS)
total_sum_squares = np.sum((features - np.mean(features))**2)
total = np.sum(total_sum_squares)

# then calculate between-cluster sum of squares (BSS)
between_SSE = (total - kmeans_obj.inertia_)

# finally calculate variance explained (BSS / TSS )
var_explained = between_SSE / total
print(f"Variance Explained: {var_explained:.4f} or {var_explained*100:.2f}%")

1683.037484618998
Variance Explained: 0.4338 or 43.38%

In [33]:
# calculate silhouette score

from sklearn.metrics import silhouette_score
ss = silhouette_score(features, kmeans_obj.labels_)
print(f"Silhouette score: {ss}")

Silhouette score: 0.1561876298190825

In [ ]:
# elbow curve: first calculate within-cluster sum of squares (WCSS) for different k

wcss = []
for i in range(1, 11):
    kmeans_obj = KMeans(n_clusters=i, random_state=42).fit(features)
    wcss.append(kmeans_obj.inertia_)

In [ ]:
# elbow curve: plot using the WCSS for different k

elbow_data_Dem = pd.DataFrame({"k": range(1, 11), "wcss": wcss})
fig = px.line(elbow_data_Dem, x="k", y="wcss", title="Elbow Method using WCSS")
fig.show()

In [ ]:
# elbow curve: first calculate within-cluster sum of squares (WCSS) for different k

sss = []
for i in range(2, 11): # silhouette score cannot run for k=1
    kmeans_obj = KMeans(n_clusters=i, random_state=42).fit(features)
    ss = silhouette_score(features, kmeans_obj.labels_)
    sss.append(ss)

In [ ]:
# elbow curve: plot using the silhouette score for different k

elbow_data_Dem = pd.DataFrame({"k": range(2, 11), "ss": sss})
fig = px.line(elbow_data_Dem, x="k", y="ss", title="Elbow Method using Silhouette Score")
fig.show()

In [ ]:
# WCSS: elbow bends at k=2
# silhouette score: highest at k=2

# based on the two elbow plots, best k = 2

kmeans_obj_2 = KMeans(n_clusters=2, random_state=42).fit(features)

In [ ]:
# visualize clusters in 3D

fig = px.scatter_3d(
    X_scaled, x="eFG%", y="PTS", z="G", # 3 chosen variables
    color="2025-26", # color indicates salary
    symbol=kmeans_obj.labels_, # shape indicates cluster
    hover_data=["Player"]) # check which point is which Player
fig.show(renderer="browser")

In [ ]:
# final model evaluation: calculate variance explained

# first calculate total sum of squares (TSS)
total_sum_squares = np.sum((features - np.mean(features))**2)
total = np.sum(total_sum_squares)

# then calculate between-cluster sum of squares (BSS)
between_SSE = (total - kmeans_obj_2.inertia_)

# finally calculate variance explained (BSS / TSS )
var_explained = between_SSE / total
print(f"Variance Explained: {var_explained:.4f} or {var_explained*100:.2f}%")

Variance Explained: 0.2368 or 23.68%

In [ ]:
# final model evaluation: calculate silhouette score

from sklearn.metrics import silhouette_score
ss = silhouette_score(features, kmeans_obj_2.labels_)
print(f"Silhouette score: {ss}")

Silhouette score: 0.2256897568000205

What sort of players do we want?

We want players that perform well but are underpaid. In other words, we want players that are shown as circles ( = clustered as the relatively better performers) with a dark color ( = getting relatively low salary) in the 3D visualization. We do NOT want players that are shown as squares ( = clustered as the relatively worse performers) with a light color ( = getting relatively high salary). We also want to check the individual players' stats to ensure they are the player we want before making any final decisions.